package it.unibo.protocol

object ConfigParameters:

  val LOCALHOST = "127.0.0.1"
  val ACTOR_SYSTEM_NAME = "GameCluster"

  val MOTHER_PORT = 19000
  val RANDOM_PORT = 0

  val DEFAULT_PLAYER_SIZE = 200
  val DEFAULT_FOOD_SIZE = 100
  val DEFAULT_WORLD_WIDTH = 1000
  val DEFAULT_WORLD_HEIGHT = 1000
  val INIT_FOOD_NUMBER = 100
  val CENTER_X = DEFAULT_WORLD_WIDTH / 2
  val CENTER_Y = DEFAULT_WORLD_HEIGHT / 2
